titanic <- read.csv("C:\\Users\\admin\\Desktop\\Kaggle Titanic\\train.csv" , header=TRUE, sep=",")
View(titanic)
head(titanic,10)
tail(titanic,10)
names(titanic)
str(titanic)
summary(titanic)
data=c(1:10)
data
fivenum(data)
fivenum(titanic['Age'])
mean(titanic$Age,na.rm = TRUE)
median(titanic$Age,na.rm = TRUE)
sd(titanic$Age,na.rm = TRUE)
hist(titanic$Age,na.rm = TRUE)