etfprices <- read.csv("C:/Users/admin/Desktop/Kaggle Titanic/ETF prices.csv", header=TRUE, sep=",")
View(etfprices)
head(etfprices,15)
tail(etfprices,20)
names(etfprices) 
str(etfprices)
summary(etfprices) 
data=c(1:10)
data
fivenum(data)
fivenum(etfprices['high'])
mean(etfprices$high, na.rm = TRUE)
median(etfprices$high, na.rm = TRUE)
sd(etfprices$high, na.rm = TRUE)
hist(etfprices$high, na.rm = TRUE)
mean(etfprices$low, na.rm = TRUE)
LinearModu <- lm(high~open, data=etfprices)
print(LinearModu)
summary(LinearModu)